// const data = {
//   products: [
//     {
//       name: 'Nvidia RTX 3080',
//       slug: 'Nvidia-RTX-3080',
//       category: 'GPU',
//       image: '/images/RTX-3080.jpeg',
//       price: 850,
//       countInStock: 10,
//       brand: 'Nvidia',
//       rating: 4.5,
//       numReviews: 10,
//       description: 'Description of 3080',
//     },
//     {
//       name: 'AMD RX 6800XT',
//       slug: 'AMD-RX-6800XT',
//       category: 'GPU',
//       image: '/images/RX-6800.jpeg',
//       price: 700,
//       countInStock: 10,
//       brand: 'AMD',
//       rating: 4.5,
//       numReviews: 10,
//       description: 'description of 6800XT',
//     },
//     {
//       name: 'Nvidia RTX 3050',
//       slug: 'Nvidia-RTX-3050',
//       category: 'GPU',
//       image: '/images/RTX-3050.jpeg',
//       price: 250,
//       countInStock: 10,
//       brand: 'Nvidia',
//       rating: 4.5,
//       numReviews: 10,
//       description: 'description of 3050',
//     },
//     {
//       name: 'AMD RX 5700XT',
//       slug: 'AMD-RX-5700XT',
//       category: 'GPU',
//       image: '/images/Rx-5700-XT.jpeg',
//       price: 250,
//       countInStock: 10,
//       brand: 'AMD',
//       rating: 4.5,
//       numReviews: 10,
//       description: 'description of 5700XT',
//     },
//   ],
// };
// export default data;
